// Generated by Scripts/embed-git-revision.sh — do not edit by hand.
// Placeholder values are committed so the target compiles (e.g. Xcode Cloud) before the script runs.

enum GitRevision {
    static let shortHash: String = "unknown"
    static let fullHash: String = "unknown"
}
