#!/bin/sh
set -e
OUT="${SRCROOT}/CopyPasta/GitRevision.generated.swift"
COMMIT=$(git -C "${SRCROOT}" rev-parse HEAD 2>/dev/null || echo "unknown")
SHORT=$(git -C "${SRCROOT}" rev-parse --short HEAD 2>/dev/null || echo "unknown")
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
// Generated by Scripts/embed-git-revision.sh — do not edit.

enum GitRevision {
    static let shortHash: String = "${SHORT}"
    static let fullHash: String = "${COMMIT}"
}
EOF
